export const JSONList = {
    "AF": "Afghanistan",
    "AX": ["Åland Islands", "Aland Islands"],
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": ["Antigua and Barbuda", "Antigua", "Barbuda"],
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": ["Bosnia and Herzegovina", "Bosnia"],
    "BW": "Botswana",
    "BR": ["Brazil", "Federative Republic of Brazil"],
    "IO": "British Indian Ocean Territory",
    "BN": ["Brunei Darussalam", "Brunei"],
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": ["Central African Republic", "CAR"],
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": ["Congo", "Congo-Brazzaville"],
    "CD": ["The Democratic Republic of the Congo", "DRC", "DRC", "DR Congo", "Congo-Kinshasa"],
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": ["Cote D\"Ivoire", "Ivory coast"],
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": ["Czech Republic", "Czechia"],
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": ["Falkland Islands", "Islas Malvinas", "Falklands"],
    "FO": ["Faroe Islands"],
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "VA": ["Vatican City", "Holy See", "The Vatican"],
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": ["Italy", "Italia"],
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "North Korea",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": ["Libyan Arab Jamahiriya", "Libya"],
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": ["Macao", "Macau"],
    "MK": "Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": ["Maldives", "The Maldives"],
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": ["Federated States of Micronesia", "Micronesia"],
    "MD": ["Republic of Moldova", "Moldova"],
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": ["Myanmar", "Burma"],
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": ["Netherlands", "Holland"],
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestine",
    "PA": "Panama",
    "PG": ["Papua New Guinea", "Papua"],
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": ["The Philippines", "Philippines"],
    "PN": ["Pitcairn", "Pitcairn Islands"],
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": ["Russian Federation", "Russia"],
    "RW": "Rwanda",
    "SH": ["Saint Helena", "St Helena", "St. Helena"],
    "KN": ["Saint Kitts and Nevis", "Saint Kitts & Nevis", "St Kitts and Nevis", "St Kitts & Nevis", "St. Kitts and Nevis", "St. Kitts & Nevis"],
    "LC": ["Saint Lucia", "St. Lucia", "St Lucia"],
    "PM": ["Saint Pierre and Miquelon", "Saint Pierre & Miquelon", "St Pierre and Miquelon", "St Pierre & Miquelon", "St. Pierre and Miquelon", "St. Pierre & Miquelon"],
    "VC": ["Saint Vincent and the Grenadines", "Saint Vincent & the Grenadines", "St Vincent and the Grenadines", "St Vincent & the Grenadines", "St. Vincent and the Grenadines", "St. Vincent & the Grenadines"],
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": ["Sao Tome and Principe", "São Tomé e Príncipe", "Sao Tome & Principe"],
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": ["South Georgia and the South Sandwich Islands", "South Georgia", "South Georgia & the South Sandwich Islands"],
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SZ": ["Swaziland", "Eswatini"],
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": ["Syrian Arab Republic", "Syria"],
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": ["East Timor", "Timor Leste", "Timor-Leste"],
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": ["Trinidad and Tobago", "Trinidad", "Trinidad & Tobago"],
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": ["Turks and Caicos Islands", "Turks & Caicos Islands"],
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": ["United Arab Emirates", "UAE"],
    "GB": ["United Kingdom", "UK"],
    "US": ["United States", "United States of America", "America", "US", "USA"],
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": ["Virgin Islands, British", "Virgin Islands"],
    "VI": ["Virgin Islands, US", "Virgin Islands, USA", "Virgin Islands"],
    "WF": ["Wallis and Futuna", "Wallis & Futuna"],
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}

// 10, 25, 50
export const countryPointValues = {
    "AF": 25,
    "AX": 50,
    "AL": 25,
    "DZ": 25,
    "AS": 50,
    "AD": 50,
    "AO": 25,
    "AI": 50,
    "AQ": 10,
    "AG": 25,
    "AR": 10,
    "AM": 10,
    "AW": 50,
    "AU": 10,
    "AT": 10,
    "AZ": 10,
    "BS": 25,
    "BH": 25,
    "BD": 10,
    "BB": 25,
    "BY": 25,
    "BE": 10,
    "BZ": 25,
    "BJ": 25,
    "BM": 50,
    "BT": 25,
    "BO": 25,
    "BA": 25,
    "BW": 25,
    "BR": 10,
    "IO": 50,
    "BN": 25,
    "BG": 10,
    "BF": 25,
    "BI": 25,
    "KH": 25,
    "CM": 25,
    "CA": 10,
    "CV": 50,
    "KY": 50,
    "CF": 25,
    "TD": 10,
    "CL": 10,
    "CN": 10,
    "CX": 50,
    "CC": 50,
    "CO": 25,
    "KM": 50,
    "CG": 25,
    "CD": 25,
    "CK": 50,
    "CR": 25,
    "CI": 25,
    "HR": 25,
    "CU": 10,
    "CY": 10,
    "CZ": 10,
    "DK": 10,
    "DJ": 25,
    "DM": 50,
    "DO": 25,
    "EC": 25,
    "EG": 10,
    "SV": 25,
    "GQ": 25,
    "ER": 25,
    "EE": 10,
    "ET": 10,
    "FK": 25,
    "FO": 50,
    "FJ": 50,
    "FI": 10,
    "FR": 10,
    "GF": 25,
    "PF": 50,
    "TF": 50,
    "GA": 25,
    "GM": 25,
    "GE": 10,
    "DE": 10,
    "GH": 25,
    "GI": 50,
    "GR": 10,
    "GL": 10,
    "GD": 50,
    "GP": 50,
    "GU": 50,
    "GT": 50,
    "GG": 50,
    "GN": 25,
    "GW": 25,
    "GY": 25,
    "HT": 25,
    "VA": 25,
    "HN": 25,
    "HK": 10,
    "HU": 10,
    "IS": 10,
    "IN": 10,
    "ID": 10,
    "IR": 10,
    "IQ": 10,
    "IE": 10,
    "IM": 50,
    "IL": 10,
    "IT": 10,
    "JM": 10,
    "JP": 10,
    "JE": 50,
    "JO": 25,
    "KZ": 25,
    "KE": 10,
    "KI": 50,
    "KP": 10,
    "KR": 10,
    "KW": 25,
    "KG": 25,
    "LA": 25,
    "LV": 10,
    "LB": 25,
    "LS": 25,
    "LR": 10,
    "LY": 10,
    "LI": 50,
    "LT": 10,
    "LU": 25,
    "MO": 25,
    "MK": 25,
    "MG": 10,
    "MW": 25,
    "MY": 25,
    "MV": 50,
    "ML": 25,
    "MT": 25,
    "MH": 50,
    "MQ": 50,
    "MR": 25,
    "MU": 50,
    "YT": 10,
    "MX": 10,
    "FM": 50,
    "MD": 25,
    "MC": 25,
    "MN": 10,
    "ME": 25,
    "MS": 50,
    "MA": 25,
    "MZ": 25,
    "MM": 25,
    "NA": 25,
    "NR": 50,
    "NP": 10,
    "NL": 10,
    "NC": 50,
    "NZ": 10,
    "NI": 25,
    "NE": 25,
    "NG": 10,
    "NU": 50,
    "NF": 50,
    "MP": 50,
    "NO": 10,
    "OM": 25,
    "PK": 10,
    "PW": 50,
    "PS": 25,
    "PA": 25,
    "PG": 25,
    "PY": 25,
    "PE": 10,
    "PH": 10,
    "PN": 50,
    "PL": 10,
    "PT": 10,
    "PR": 25,
    "QA": 25,
    "RE": 50,
    "RO": 25,
    "RU": 10,
    "RW": 25,
    "SH": 50,
    "KN": 50,
    "LC": 50,
    "PM": 50,
    "VC": 50,
    "WS": 50,
    "SM": 50,
    "ST": 50,
    "SA": 10,
    "SN": 25,
    "RS": 25,
    "SC": 50,
    "SL": 25,
    "SG": 25,
    "SK": 25,
    "SI": 25,
    "SB": 50,
    "SO": 25,
    "ZA": 10,
    "GS": 50,
    "ES": 10,
    "LK": 25,
    "SD": 10,
    "SR": 25,
    "SZ": 25,
    "SE": 10,
    "CH": 10,
    "SY": 10,
    "TW": 25,
    "TJ": 25,
    "TZ": 25,
    "TH": 10,
    "TL": 25,
    "TG": 25,
    "TK": 50,
    "TO": 50,
    "TT": 25,
    "TN": 25,
    "TR": 10,
    "TM": 25,
    "TC": 50,
    "TV": 50,
    "UG": 25,
    "UA": 10,
    "AE": 25,
    "GB": 10,
    "US": 10,
    "UY": 25,
    "UZ": 25,
    "VU": 50,
    "VE": 25,
    "VN": 25,
    "VG": 50,
    "VI": 50,
    "WF": 50,
    "EH": 50,
    "YE": 25,
    "ZM": 25,
    "ZW": 25
}