export const countryCodeToCountryNameMap = {
    "AF": "Afghanistan",
    "AX": ["Åland Islands", "Aland Islands"],
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": ["Antigua and Barbuda", "Antigua", "Barbuda"],
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": ["Bosnia and Herzegovina", "Bosnia"],
    "BW": "Botswana",
    "BR": ["Brazil", "Federative Republic of Brazil"],
    "IO": "British Indian Ocean Territory",
    "BN": ["Brunei Darussalam", "Brunei"],
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": ["Central African Republic", "CAR"],
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": ["Congo", "Congo-Brazzaville"],
    "CD": ["The Democratic Republic of the Congo", "DRC", "DRC", "DR Congo", "Congo-Kinshasa"],
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": ["Cote D\'Ivoire", "Ivory Coast"],
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": ["Czech Republic", "Czechia"],
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": ["Falkland Islands", "Islas Malvinas", "Falklands"],
    "FO": ["Faroe Islands"],
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": ["Germany", "Deutschland"],
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "VA": ["Vatican City", "Holy See", "The Vatican"],
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": ["Italy", "Italia"],
    "JM": "Jamaica",
    "JP": ["Japan", "Nihon"],
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "North Korea",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": ["Libyan Arab Jamahiriya", "Libya"],
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": ["Macao", "Macau"],
    "MK": "Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": ["Maldives", "The Maldives"],
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": ["Federated States of Micronesia", "Micronesia"],
    "MD": ["Republic of Moldova", "Moldova"],
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": ["Myanmar", "Burma"],
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": ["Netherlands", "Holland"],
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestine",
    "PA": "Panama",
    "PG": ["Papua New Guinea", "Papua"],
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": ["The Philippines", "Philippines"],
    "PN": ["Pitcairn", "Pitcairn Islands"],
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": ["Russian Federation", "Russia"],
    "RW": "Rwanda",
    "SH": ["Saint Helena", "St Helena", "St. Helena"],
    "KN": ["Saint Kitts and Nevis", "Saint Kitts & Nevis", "St Kitts and Nevis", "St Kitts & Nevis", "St. Kitts and Nevis", "St. Kitts & Nevis"],
    "LC": ["Saint Lucia", "St. Lucia", "St Lucia"],
    "PM": ["Saint Pierre and Miquelon", "Saint Pierre & Miquelon", "St Pierre and Miquelon", "St Pierre & Miquelon", "St. Pierre and Miquelon", "St. Pierre & Miquelon"],
    "VC": ["Saint Vincent and the Grenadines", "Saint Vincent & the Grenadines", "St Vincent and the Grenadines", "St Vincent & the Grenadines", "St. Vincent and the Grenadines", "St. Vincent & the Grenadines"],
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": ["Sao Tome and Principe", "São Tomé e Príncipe", "Sao Tome & Principe"],
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": ["South Georgia and the South Sandwich Islands", "South Georgia", "South Georgia & the South Sandwich Islands"],
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SZ": ["Swaziland", "Eswatini"],
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": ["Syrian Arab Republic", "Syria"],
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": ["East Timor", "Timor Leste", "Timor-Leste"],
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": ["Trinidad and Tobago", "Trinidad", "Trinidad & Tobago"],
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": ["Turks and Caicos Islands", "Turks & Caicos Islands"],
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": ["United Arab Emirates", "UAE"],
    "GB": ["United Kingdom", "UK", "Great Britain", "GB"],
    "US": ["United States", "United States of America", "America", "US", "USA"],
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": ["Virgin Islands, British", "Virgin Islands"],
    "VI": ["Virgin Islands, US", "Virgin Islands, USA", "Virgin Islands"],
    "WF": ["Wallis and Futuna", "Wallis & Futuna"],
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}
